AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceId:
    Description: "EC2 Instance ID"
    Type: "String"
    Default: "i-0abcdef1234567890"  # 適当なデフォルトのインスタンスID

Mappings:
  AlarmThresholds:
    CPUUtilization:
      Threshold: 80
    DiskReadOps:
      Threshold: 100
    NetworkIn:
      Threshold: 50000

Resources:
  MyAlarm1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-CPUUtilization-Alarm"
      MetricName: "CPUUtilization"
      Namespace: "AWS/EC2"
      Statistic: "Average"
      Period: 300
      EvaluationPeriods: 2
      Threshold: !FindInMap [AlarmThresholds, CPUUtilization, Threshold]
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions: []
      Dimensions:
        - Name: "InstanceId"
          Value: !Ref InstanceId


Outputs:
  Alarm1Name:
    Description: "Name of the first CloudWatch alarm."
    Value: !Ref MyAlarm1

  Alarm2Name:
    Description: "Name of the second CloudWatch alarm."
    Value: !Ref MyAlarm2

  Alarm3Name:
    Description: "Name of the third CloudWatch alarm."
    Value: !Ref MyAlarm3